schemaVersion: 3.0.0
entityType: Application
id: 01KY6Z7BD8J607T07GS5NCN9RN
key: zto.connect
label: 中通宝盒
packageId: com.zto.connect.fat
platform: android
status: active
provenance:
  sourceType: legacy_uikg_v2_import
  sourceEntityId: 01KY6Z7BD8J607T07GS5NCN9RN
